%YAML:1.0
cameras:
     - {T_SC:
        [1.0, 0.0, 0.0, -0.0302200001,
         0.0, 1.0, 0.0,  0.0074000000,
         0.0, 0.0, 1.0,  0.0160200000,
          0.0, 0.0, 0.0, 1.0000000000],
        image_dimension: [640, 480],
        distortion_coefficients: [0.336559997650154, 0.13610740652468126, 0.024529779358255937, 0.041050039886663975],
        distortion_type: equidistant,
        focal_length: [384.3723240427625, 385.2106750321885],
        principal_point: [317.7259149572296, 239.3844686609677]}

     - {T_SC:
        [1.0, 0.0, 0.0,  0.0646901205,
         0.0, 1.0, 0.0,  0.0074000000,
         0.0, 0.0, 1.0,  0.0160200000,
          0.0, 0.0, 0.0, 1.0000000000],
        image_dimension: [640, 480],
        distortion_coefficients: [0.3373786723950992, 0.14775327112668654, -0.02787428908368021, 0.0985151942241339],
        distortion_type: equidistant,
        focal_length: [384.23752937945306, 385.10239073262653],
        principal_point: [318.1585024202477, 239.5129254445977]}

# additional camera parameters
camera_parameters:
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance
    image_delay: 0.0 # [s] timestamp_camera_correct = timestamp_camera - image_delay -0.00780146
    online_calibration: # some parameters to set the online 
        do_extrinsics: false # Do we online-calibrate extrinsics?
        sigma_r: 0.001 # T_SCi position prior stdev [m] 
        sigma_alpha: 0.01 # T_SCi orientation prior stdev [rad]

# the IMU sensor model
imu_parameters:
    used: true # enable IMU
    a_max: 160.0 # acceleration saturation [m/s^2]
    g_max: 10.0 # gyro saturation [rad/s]
    sigma_g_c: 0.00278 # gyro noise density [rad/s/sqrt(Hz)]
    sigma_bg: 0.03 # gyro bias prior [rad/s]
    sigma_a_c: 0.0252 # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_ba: 0.01 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 0.0008 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 0.04 # 0.04 accelerometer drift noise density [m/s^2/sqrt(Hz)]
    a0: [0.0,0.0,0.0] #[-0.0691081, 0.0215465, 0.315693] # [ -0.1, 0.1, 0.4 ] Initial accelerometer bias [m/s^2]
    g0: [0.0, 0.0, 0.0] #[-0.00152201, -0.00139254, -0.000370433] # Initial gyro bias [rad/s]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    T_BS: 
        [ 1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0 ]

# frontend: detection etc. 
frontend_parameters:
    detection_threshold: 40.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 4.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 55.0 # BRISK descriptor matching threshold
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 800 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.7 # minimum field-of-view overlap
    use_cnn: false # use the CNN (if available) to filter out dynamic content / sky
    parallelise_detection: true # Run parallel detect & describe.
    num_matching_threads: 4 # Parallelise matching with this number of threads.


# estimator parameters
estimator_parameters:
    num_keyframes: 7 # number of keyframes in optimisation window
    num_loop_closure_frames: 5 # number of loop closure frames in optimisation window
    num_imu_frames: 5 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: false # Whether to run a full final BA
    enforce_realtime: true # whether to limit the time budget for optimisation 
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.03 # time budget for realtime optimisation [s]
    realtime_num_threads: 4 # number of threads for the realtime optimisation
    full_graph_iterations: 500 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 1 # number of threads for the full (background) optimisation

# some options for how and what to output
output_parameters:
    display_matches: false  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
    publish_imu_propagated_state: false # Should the state that is propagated with IMU messages be published or just the optimised ones?
    imu_propagated_state_publishing_rate: 100.0

# some options for gps mode
gps_parameters:
    use_gps: true # is gps available
    data_type: "geodetic" # "cartesian" | "geodetic": format of GPS data
    observability_threshold: 10.0 # threshold when GPS extrinsics are assumed to become observable
    variance_threshold: 50.0 # threshold for the max() operation on the chi square error
    r_SA: [ 0.018 , 0.007, -0.104 ] # antenna position relative to (IMU) sensor frame 
    yaw_error_threshold: 0.1 # threshold for initialization (in degrees)
    gps_fusion_mode: 4 # 1: do svd initialization only once | 2: do SVD initialisation in every step | 4: do position + full alignment

