%YAML:1.2
# SPDX-FileCopyrightText: 2021 Smart Robotics Lab, Imperial College London, Technical University of Munich
# SPDX-License-Identifier: CC0-1.0

general:
  sensor_type:                "depth" # depth | ouster [not yet supported] | leica
  results_directory:          "/home/stud/zxuh/datasets/results"
  #results_directory:         "/srv/submapping_data/ros/submaps2"
  #results_directory:          "/srv/Users/Boche/Documents/Datasets/Digiforest"
  integration_type:           "ray"  # ray | rangeImage; option not yet supported, not used if sensor_type depth
  submap_time_threshold:      15.0  # taken from Tommaso
  submap_state_buffer:        1 #Buffer, if in 10 states we have notcreated a submap we start integrating it into supereight
  submap_kf_threshold:        3
  sensor_measurement_downsampling: 1
  depth_image_resolution_downsampling: 2

map:
  dim:                        [25.6, 25.6, 25.6] # [15., 15., 15.] # [100., 140., 50.]
  res:                        0.1
  free_space_res:             0.1 # free space resolution

data:
  # tsdf
  truncation_boundary_factor: 8
  max_weight:                 100

  # occupancy
  surface_boundary:           0
  min_occupancy:              -100
  max_occupancy:               100
  log_odd_min:                -5.015
  log_odd_max:                 5.015
  fs_integr_scale:            1
  const_surface_thickness:    false
  uncertainty_model:          linear
  tau_min_factor:             3
  tau_max_factor:             12
  k_tau:                      0.05
  sigma_min_factor:           1         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  sigma_max_factor:           3         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  k_sigma:                    0.05

  # lidar ray integration
  k_scale:                    6e-03

sensor:
  # Sim Realsense / Depth cam
  width:                      640
  height:                     480
  fx:                         390.598938
  fy:                         390.598938
  cx:                         320.0
  cy:                         240.0
  near_plane:                 0.2
  far_plane:                  20.0
  scale:                      1.0     #Scale factor to apply to the depth images receiver from the camera, system works in m
  T_BS:                       [1.0, 0.0, 0.0, -0.0302200001,
                                0.0, 1.0, 0.0,  0.0074000000,
                                0.0, 0.0, 1.0,  0.0160200000,
                                0.0, 0.0, 0.0, 1.0000000000]

  # Introduce new notation to be consistent with OKVIS, needed here: depth sensor [camera or lidar frame, D ] w.r.t. IMU [S in OKVIS]
  T_SD:                       []

  # Sim Lidar
  # width:                      360
  # height:                     180
  # elevation_angles:           []
  # azimuth_angles:             []
  # near_plane:                 0.8
  # far_plane:                  30.0
  # elevation_resolution_angle: 0.086 # only used for ray-based integration [degree]
  # azimuth_resolution_angle:   0.002 # only used for ray-based integration [degree]
  # T_BS:                       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.05, 0.0, 0.0, 0.0, 1.0]
