%YAML:1.2
# SPDX-FileCopyrightText: 2021 Smart Robotics Lab, Imperial College London, Technical University of Munich
# SPDX-License-Identifier: CC0-1.0

map:
  dim:                        [102.4, 102.4, 102.4]
  res:                        0.1
  free_space_res:             0.2 # free space resolution

data:
  # tsdf
  truncation_boundary_factor: 8
  max_weight:                 100

  # occupancy
  surface_boundary:           0
  min_occupancy:              -100
  max_occupancy:               100
  log_odd_min:                -5.015
  log_odd_max:                 5.015
  fs_integr_scale:            1
  const_surface_thickness:    false
  uncertainty_model:          linear
  tau_min_factor:             3
  tau_max_factor:             12
  k_tau:                      0.05
  sigma_min_factor:           1         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  sigma_max_factor:           3         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  k_sigma:                    0.05

  # lidar ray integration
  k_scale:                    5e-04

sensor:
  width:                      360
  height:                     180
  elevation_angles:           []
  azimuth_angles:             []
  near_plane:                 0.8
  far_plane:                  30.0
  T_BS:                       [0.703850921920426,   0.710042354007461,   0.020826242473285,  -0.071641078341150,   -0.709921628518391,   0.704141660713858,  -0.013992693209085,  -0.002790140465079,   -0.024600025830421,  -0.004936230474986,   0.999685183150121,   0.012269585308958, 0., 0., 0., 1.] # Body - to - sensor (LiDAR) for only mapping
  #T_BS:                       [0.0081, -0.0083, -0.9999, -0.0729, -0.7830, -0.6221, -0.0012, 0.0011, -0.6220, 0.7829, -0.0115, 0.0351, 0., 0., 0., 1.] # Body (=IMU) - to - sensor (=LiDAR) for integration into OKVIS
  elevation_resolution_angle: 0.4 # only used for ray-based integration [degree]
  azimuth_resolution_angle:   0.35 # only used for ray-based integration [degree]

tracker:
  iterations:                 [10, 5, 4]
  dist_threshold:             0.1
  normal_threshold:           0.8
  track_threshold:            0.15
  icp_threshold:              0.00001

reader:
  reader_type:                "leica"
  sequence_path:              "/home/boche/Documents/Datasets/NewerCollege/LeicaFormat/last"
  ground_truth_file:          "/home/boche/Documents/Datasets/NewerCollege/LeicaFormat/last/trajectory.csv"
  fps:                        0.0
  drop_frames:                false
  verbose:                    0
  # following parameters are only used for Leica BLK LiDAR sensor
  leica_reader_type:          "ray" # "ray" | "rangeImage"
  T_BS:                       [0.703850921920426,   0.710042354007461,   0.020826242473285,  -0.071641078341150,   -0.709921628518391,   0.704141660713858,  -0.013992693209085,  -0.002790140465079,   -0.024600025830421,  -0.004936230474986,   0.999685183150121,   0.012269585308958, 0., 0., 0., 1.] #Body - to - sensor (LiDAR) for only mapping
  #T_BS:                       [0.0081, -0.0083, -0.9999, -0.0729, -0.7830, -0.6221, -0.0012, 0.0011, -0.6220, 0.7829, -0.0115, 0.0351, 0., 0., 0., 1.] # Body (=IMU) - to - sensor (=LiDAR) for integration into OKVIS
  scan_time_interval:         0.2 # only for "rangeImage; size of interval that lidar measurements are clustered together
  use_motion_comp:            true
  width:                      360 # only for "rangeImage; should match sensor.width
  height:                     180 # only for "rangeImage; should match sensor.height

app:
  enable_ground_truth:        true
  enable_rendering:           true
  enable_gui:                 true
  mesh_path:                  "/home/boche/Documents/Datasets/NewerCollege/LeicaFormat/last/meshes/ray_based"
  slice_path:                 "/home/boche/Documents/Datasets/NewerCollege/LeicaFormat/last/meshes/ray_based"
  structure_path:             "/home/boche/Documents/Datasets/NewerCollege/LeicaFormat/last/meshes/ray_based"
  sensor_downsampling_factor: 1
  tracking_rate:              1
  integration_rate:           1
  rendering_rate:             1
  meshing_rate:               500000
  max_frames:                 -1
  log_file:                   "/home/boche/Documents/Datasets/NewerCollege/LeicaFormat/last/meshes/ray_based/log.csv"